### ISSUE TITLE
Archipel node crash with error: WouldBlock, message: "Resource temporarily unavailable

### ISSUE THREAD

**Issue by branciard** [luguslabs/archipel#212]
```
Version: 2.0.0-x86_64-linux-gnu

stack backtrace:
   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:476
   2: rust_begin_unwind
             at src/libstd/panicking.rs:380
   3: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:334
   4: tokio_threadpool::pool::Pool::spawn_thread
   5: tokio_threadpool::pool::Pool::signal_work
   6: ::spawn
   7: tokio::runtime::threadpool::Runtime::spawn
   8: jsonrpc_server_utils::reactor::RpcEventLoop::with_name
   9: jsonrpc_server_utils::reactor::UninitializedExecutor::init_with_name
  10: ::next
  11: ::from_iter
  12: core::iter::adapters::process_results
  13: sc_rpc_server::inner::start_http
  14: sc_service::start_rpc_servers
  15: sc_service::builder::ServiceBuilder::build
  16: archipel::service::new_full
  17: sc_cli::ParseAndPrepareRun::run
  18: archipel::cli::run
  19: archipel::main
  20: std::rt::lang_start::{{closure}}
  21: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
      std::panicking::try::do_call
             at src/libstd/panicking.rs:305
  22: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  23: std::panicking::try
             at src/libstd/panicking.rs:281
      std::panic::catch_unwind
             at src/libstd/panic.rs:394
      std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  24: main
  25: __libc_start_main
  26: _start


Thread 'main' panicked at 'failed to spawn worker thread: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.17/src/pool/mod.rs:390

This is a bug. Please report it at:

archipel.id
```

**Comment by branciard** [comment]
no link to substrate chain. It happens when OS has freeze ( too many open files ? )
